import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Mail, Phone, MapPin, Building, AlertCircle, CheckCircle } from 'lucide-react';
// =================================================================
// COMPONENTE PRINCIPAL
// =================================================================
export const ContactInfoSection = ({ email = '', telefono = '', celular = '', direccion = '', domicilio_fiscal = '', distrito = '', provincia = '', departamento = '', datosConsolidados, estado, errores, onChange, onBlur, readonly = false, expandido = true, mostrarFuentesDatos = false, }) => {
    // =================================================================
    // HELPERS
    // =================================================================
    const getFieldError = (field) => {
        return errores.find(error => error.campo === field)?.mensaje;
    };
    const hasConsolidatedData = (field) => {
        return datosConsolidados ? !!datosConsolidados[field] : false;
    };
    // const getConsolidatedValue = (field: keyof ContactoConsolidado): string => {
    //   return datosConsolidados?.[field] || '';
    // };
    // =================================================================
    // RENDER
    // =================================================================
    if (!expandido)
        return null;
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, className: "space-y-6", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: `flex-shrink-0 w-10 h-10 rounded-lg flex items-center justify-center ${estado.con_errores
                            ? 'bg-red-100 text-red-600'
                            : estado.completado
                                ? 'bg-green-100 text-green-600'
                                : 'bg-blue-100 text-blue-600'}`, children: _jsx(Mail, { className: "w-5 h-5" }) }), _jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900", children: "Informaci\u00F3n de Contacto" }), _jsx("p", { className: "text-sm text-gray-600", children: "Datos de comunicaci\u00F3n y ubicaci\u00F3n de la empresa" })] }), estado.datos_consolidados && (_jsxs("div", { className: "flex items-center gap-1 text-xs text-green-600 font-medium", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), "Datos obtenidos"] }))] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsxs("div", { className: "relative", children: [_jsxs("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: [_jsx(Mail, { className: "w-4 h-4 inline mr-1" }), "Correo Electr\u00F3nico"] }), _jsxs("div", { className: "relative", children: [_jsx("input", { type: "email", value: email, onChange: (e) => onChange('email', e.target.value), onBlur: onBlur ? () => onBlur('email') : undefined, readOnly: readonly, className: `w-full px-3 py-2 pr-10 border rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors ${getFieldError('email')
                                            ? 'border-red-300 bg-red-50'
                                            : hasConsolidatedData('email')
                                                ? 'border-green-300 bg-green-50'
                                                : 'border-gray-300'} ${readonly ? 'bg-gray-50 cursor-not-allowed' : ''}`, placeholder: "empresa@dominio.com" }), hasConsolidatedData('email') && (_jsx("div", { className: "absolute right-3 top-2 text-green-500", children: _jsx(CheckCircle, { className: "w-4 h-4" }) }))] }), getFieldError('email') && (_jsxs("p", { className: "text-red-500 text-sm mt-1 flex items-center gap-1", children: [_jsx(AlertCircle, { className: "w-4 h-4" }), getFieldError('email')] })), mostrarFuentesDatos && hasConsolidatedData('email') && (_jsxs("p", { className: "text-xs text-green-600 mt-1", children: ["Obtenido de: ", estado.fuente_datos || 'Sistema consolidado'] }))] }), _jsxs("div", { className: "relative", children: [_jsxs("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: [_jsx(Phone, { className: "w-4 h-4 inline mr-1" }), "Tel\u00E9fono Principal"] }), _jsxs("div", { className: "relative", children: [_jsx("input", { type: "tel", value: telefono, onChange: (e) => onChange('telefono', e.target.value), onBlur: onBlur ? () => onBlur('telefono') : undefined, readOnly: readonly, className: `w-full px-3 py-2 pr-10 border rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors ${getFieldError('telefono')
                                            ? 'border-red-300 bg-red-50'
                                            : hasConsolidatedData('telefono')
                                                ? 'border-green-300 bg-green-50'
                                                : 'border-gray-300'} ${readonly ? 'bg-gray-50 cursor-not-allowed' : ''}`, placeholder: "987654321" }), hasConsolidatedData('telefono') && (_jsx("div", { className: "absolute right-3 top-2 text-green-500", children: _jsx(CheckCircle, { className: "w-4 h-4" }) }))] }), getFieldError('telefono') && (_jsxs("p", { className: "text-red-500 text-sm mt-1 flex items-center gap-1", children: [_jsx(AlertCircle, { className: "w-4 h-4" }), getFieldError('telefono')] })), mostrarFuentesDatos && hasConsolidatedData('telefono') && (_jsxs("p", { className: "text-xs text-green-600 mt-1", children: ["Obtenido de: ", estado.fuente_datos || 'Sistema consolidado'] }))] })] }), _jsxs("div", { children: [_jsxs("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: [_jsx(Phone, { className: "w-4 h-4 inline mr-1" }), "Tel\u00E9fono Celular ", _jsx("span", { className: "text-gray-400 text-xs", children: "(opcional)" })] }), _jsx("input", { type: "tel", value: celular, onChange: (e) => onChange('celular', e.target.value), onBlur: onBlur ? () => onBlur('celular') : undefined, readOnly: readonly, className: `w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors ${readonly ? 'bg-gray-50 cursor-not-allowed' : 'border-gray-300'}`, placeholder: "987654321" })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsxs("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: [_jsx(MapPin, { className: "w-4 h-4 inline mr-1" }), "Direcci\u00F3n Principal"] }), _jsxs("div", { className: "relative", children: [_jsx("textarea", { value: direccion, onChange: (e) => onChange('direccion', e.target.value), onBlur: onBlur ? () => onBlur('direccion') : undefined, readOnly: readonly, rows: 2, className: `w-full px-3 py-2 pr-10 border rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors resize-none ${getFieldError('direccion')
                                            ? 'border-red-300 bg-red-50'
                                            : hasConsolidatedData('direccion')
                                                ? 'border-green-300 bg-green-50'
                                                : 'border-gray-300'} ${readonly ? 'bg-gray-50 cursor-not-allowed' : ''}`, placeholder: "Av. Principal 123, Urbanizaci\u00F3n Las Flores" }), hasConsolidatedData('direccion') && (_jsx("div", { className: "absolute right-3 top-2 text-green-500", children: _jsx(CheckCircle, { className: "w-4 h-4" }) }))] }), getFieldError('direccion') && (_jsxs("p", { className: "text-red-500 text-sm mt-1 flex items-center gap-1", children: [_jsx(AlertCircle, { className: "w-4 h-4" }), getFieldError('direccion')] }))] }), _jsxs("div", { children: [_jsxs("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: [_jsx(Building, { className: "w-4 h-4 inline mr-1" }), "Domicilio Fiscal ", _jsx("span", { className: "text-gray-400 text-xs", children: "(si es diferente)" })] }), _jsxs("div", { className: "relative", children: [_jsx("textarea", { value: domicilio_fiscal, onChange: (e) => onChange('domicilio_fiscal', e.target.value), onBlur: onBlur ? () => onBlur('domicilio_fiscal') : undefined, readOnly: readonly, rows: 2, className: `w-full px-3 py-2 pr-10 border rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors resize-none ${hasConsolidatedData('domicilio_fiscal')
                                            ? 'border-green-300 bg-green-50'
                                            : 'border-gray-300'} ${readonly ? 'bg-gray-50 cursor-not-allowed' : ''}`, placeholder: "Direcci\u00F3n para notificaciones legales (si es diferente a la principal)" }), hasConsolidatedData('domicilio_fiscal') && (_jsx("div", { className: "absolute right-3 top-2 text-green-500", children: _jsx(CheckCircle, { className: "w-4 h-4" }) }))] }), mostrarFuentesDatos && hasConsolidatedData('domicilio_fiscal') && (_jsx("p", { className: "text-xs text-green-600 mt-1", children: "Obtenido de: SUNAT (Domicilio fiscal registrado)" }))] })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-md font-medium text-gray-900 mb-3", children: "Ubicaci\u00F3n Geogr\u00E1fica" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: "Distrito" }), _jsxs("div", { className: "relative", children: [_jsx("input", { type: "text", value: distrito, onChange: (e) => onChange('distrito', e.target.value), onBlur: onBlur ? () => onBlur('distrito') : undefined, readOnly: readonly, className: `w-full px-3 py-2 pr-10 border rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors ${hasConsolidatedData('ciudad') // OECE puede tener ciudad que mapeamos a distrito
                                                    ? 'border-green-300 bg-green-50'
                                                    : 'border-gray-300'} ${readonly ? 'bg-gray-50 cursor-not-allowed' : ''}`, placeholder: "Lima" }), hasConsolidatedData('ciudad') && (_jsx("div", { className: "absolute right-3 top-2 text-green-500", children: _jsx(CheckCircle, { className: "w-4 h-4" }) }))] })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: "Provincia" }), _jsx("input", { type: "text", value: provincia, onChange: (e) => onChange('provincia', e.target.value), onBlur: onBlur ? () => onBlur('provincia') : undefined, readOnly: readonly, className: `w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors ${readonly ? 'bg-gray-50 cursor-not-allowed' : 'border-gray-300'}`, placeholder: "Lima" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: "Departamento" }), _jsxs("div", { className: "relative", children: [_jsx("input", { type: "text", value: departamento, onChange: (e) => onChange('departamento', e.target.value), onBlur: onBlur ? () => onBlur('departamento') : undefined, readOnly: readonly, className: `w-full px-3 py-2 pr-10 border rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors ${hasConsolidatedData('departamento')
                                                    ? 'border-green-300 bg-green-50'
                                                    : 'border-gray-300'} ${readonly ? 'bg-gray-50 cursor-not-allowed' : ''}`, placeholder: "Lima" }), hasConsolidatedData('departamento') && (_jsx("div", { className: "absolute right-3 top-2 text-green-500", children: _jsx(CheckCircle, { className: "w-4 h-4" }) }))] })] })] })] }), datosConsolidados && mostrarFuentesDatos && (_jsxs("div", { className: "mt-6 p-4 bg-blue-50 border border-blue-200 rounded-lg", children: [_jsx("h4", { className: "text-sm font-medium text-blue-800 mb-2", children: "Informaci\u00F3n de Fuentes" }), _jsxs("div", { className: "text-xs text-blue-700 space-y-1", children: [datosConsolidados.email && (_jsx("p", { children: "\u2022 Email: Obtenido del sistema consolidado" })), datosConsolidados.telefono && (_jsx("p", { children: "\u2022 Tel\u00E9fono: Obtenido del sistema consolidado" })), datosConsolidados.direccion && (_jsx("p", { children: "\u2022 Direcci\u00F3n: Obtenida del sistema consolidado" })), datosConsolidados.domicilio_fiscal && (_jsx("p", { children: "\u2022 Domicilio fiscal: Obtenido de SUNAT" }))] })] })), estado.con_advertencias && (_jsxs("div", { className: "p-3 bg-amber-50 border border-amber-200 rounded-lg", children: [_jsxs("div", { className: "flex items-center gap-2 text-amber-800 text-sm", children: [_jsx(AlertCircle, { className: "w-4 h-4" }), _jsx("span", { className: "font-medium", children: "Advertencias:" })] }), _jsxs("ul", { className: "text-amber-700 text-sm mt-1 space-y-1", children: [_jsx("li", { children: "\u2022 Verifique que los datos de contacto est\u00E9n actualizados" }), !email && _jsx("li", { children: "\u2022 Se recomienda proporcionar un email para comunicaciones" }), !telefono && _jsx("li", { children: "\u2022 Se recomienda proporcionar un tel\u00E9fono de contacto" })] })] }))] }));
};
export default ContactInfoSection;
